### ISSUE TITLE
Feature request: Possibility to define port

### ISSUE THREAD

**Issue by miukumac** [toolisticon/ssl-hostinfo-prometheus-exporter#42]
Would it be possible to allow defining port numbers for URLS_TO_CHECK?

I've tried the usual HOST:PORT but unfortunately it seems to only try 443 and ends up giving 400 on hosts that do not have SSL in the usual port. 

We have some weird cases where we run Tomcat instances (or nginx/lb) on 8443 and I would like to test these for expiring certs.

**Comment by hypery2k** [comment]
sure, could be like that then:
```
URLS_TO_CHECK=example.com:4443,example2.com:8443
```

is that what you want?

**Comment by miukumac** [comment]
Yes, that would be excellent :)

**Comment by hypery2k** [comment]
Released with [v1.4.0](https://github.com/toolisticon/ssl-hostinfo-prometheus-exporter/releases/tag/v1.4.0)
